### ISSUE TITLE
Expanding accordions makes them go behind other components

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#288]
### Warframe Hub Issue
---

**Summary (short):** Expanding collapsibles makes them go behind components that are "in front" or have the same/higher z-index, of the collapsibles.

Potential fix:  

---
**If issue, Reproduction:**
Open a bounty collapsible: turn [this](https://github.com/WFCD/warframe-hub/blob/f848741238d632bc93708d81281e29dfd5dd36f9/src/views/Timer.vue#L162) into a common function and call it on collapse/expand to force "reflow".

---
**Mockups, screenshots, evidence:**
1.  ![](https://cdn.discordapp.com/attachments/372476825596723210/574785887074779147/unknown.png)

2. ![](https://cdn.discordapp.com/attachments/372476825596723210/574785983820595230/unknown.png)

---

(Check one)
- [x] Issue
- [ ] Suggestion

**Comment by 107g** [comment]
I found a way to trigger grid update when a collapsible is toggled. It's kind of messy however since the attribute that determines the height of the panel isn't updated as well (and I can't find a way to update it).

It's hard to explain here so I'll make a 'WIP' pull request so can you see for yourself.
