### ISSUE TITLE
Revisit News Component

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#293]
### Warframe Hub Issue
---

**Summary (short):** As discussed in #291 it's harder to see all of the news at a glance.

---
**Description:** Perhaps moving to a hybrid of the two, where there's simply a carousel going of the images, but the news list is static.

---
**If issue, Reproduction:**
1. Visit [hub](https://hub.warframestat.us)

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [x] Suggestion

**Comment by TobiTenno** [comment]
From discussion with dsinn, having an area for the image above the list of news items, and show the image corresponding to what's highlit.

Something optional would be cycling through what's highlit, and so cycling through images that way?

**Comment by Psyqoo** [comment]
"having an area for the image above the list of news items"
that will be nice .. i just logged now and saw alerts from lotus .. i alt+tab to the new hub to see the news and i had to click 4 -6 times to see the news about the new alert and fyi i wasn't paying attention to the images .. i was looking for time post e.g "50d ago: news title" because the link i was looking for supposed to be the latest one, in my case it was "16m ago: get a new sigil and two weapons skins!"
while in old hub design i had to do is alt+tab and VOILA https://i.imgur.com/EDqySEq.png 
less than 1 sec and got the info i need .. only problem here is i must use CTRL+left mouse click to open in new window because the defult left click will open the link in same window and i have to reload back again to the hub 

thx guys for awesome work

**Comment by TobiTenno** [comment]
gonna keep this open until @dsinn or one of the others of us take a look at doing it as a hover to change the visible image. i did it as a list of the news items and it cycles through them

**Comment by VeloxAzo** [comment]
I much prefer how it is in old-hub and continue to use it over hub for that reason. Perhaps include a list style component that is disabled by default?

**Comment by TobiTenno** [comment]
it's already there, with the added carousel on top

**Comment by TobiTenno** [comment]
@VeloxAzo how do you feel about the current version that's a hybrid, or is it too much stuff still?

**Comment by VeloxAzo** [comment]
https://i.imgur.com/7us9F8b.png

It doesn't feel obnoxious, but the image is mostly useless as the user has no control over what they see. Would it be possible to have the corresponding image display when you hover over a link? It would be especially useful when items/rewards are being mentioned in a headline.

**Comment by TobiTenno** [comment]
it'd make it a ton harder to be consistent, but I could, theoretically. (and it's not really useless cause it tells you which it's showing, which takes just a couple seconds to switch between)

**Comment by TobiTenno** [comment]
@VeloxAzo let me know if the current PR is more like what you're looking for.

**Comment by VeloxAzo** [comment]
It's beautiful
