### ISSUE TITLE
Application error in old-hub

### ISSUE THREAD

**Issue by Psyqoo** [WFCD/warframe-hub#304]
Summary (short): 
--- 
_short description of what's wrong_

old hub link is not working .. it shows an Application error

Reproduction:
---
_1. I did this_
go to https://old-hub.warframestat.us/

_3. the error will show immediately ..the Error text: 

(Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail)

Screenshots, evidence:
https://i.imgur.com/3titq7F.png

**Comment by TobiTenno** [comment]
Old and new are offline because we use a free hosting option, and we have no way of increasing the allotted time without spending money on it. This is due to hosting both versions on the same heroku account and running out of free Dyno hours. I'm looking for an alternative for June, but this is how it is until then.
