### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by alexkoala** [WFCD/warframe-hub#376]
Summary (short):
---
Multilingual support.

Mockups:
---
![1](https://user-images.githubusercontent.com/44674417/70418058-f7f25000-1aa5-11ea-84ef-c76a1d63ebff.png)
![2](https://user-images.githubusercontent.com/44674417/70418063-f9bc1380-1aa5-11ea-9f35-10e673f2396e.png)

**Comment by TobiTenno** [comment]
if you'd like to put in a little bit to do the initial bit, that's fine, or i'll try to get some initial bits on this. can't promise everything, since a lot of it is super-hardcoded rn and we don't have an i18n framework in place yet, but i'd like to look into the capability

the sad truth will be that we'll probably always design and target english, but if we get help/input to keep making things usable for as many ppl as possible

**Comment by TobiTenno** [comment]
got the initial bit (switching worldstate) done:
![image](https://user-images.githubusercontent.com/7128721/70482771-07749780-1aac-11ea-9b96-19d9276665da.png)

**Comment by TobiTenno** [comment]
@alexkoala once i do the initial release with the english versions, i'll need help with the translations. for similar projects, i've opened up a crowdin project. does that sound ok to you?

**Comment by alexkoala** [comment]
Yes :smiley:
