### ISSUE TITLE
Event Support (Formorian and Razorback)

### ISSUE THREAD

**Issue by EricSihaoLin** [WFCD/warframe-hub#43]
### Warframe Hub Issue
---
---

**Summary (short):**
---

Include event support

**Description:**
---

Include events such as Formorian and Razorback

**If issue, Reproduction:**
---

**Mockups, screenshots, evidence:**
---

(Check one)
- [ ] Issue
- [X] Suggestion

**Comment by aliasfalse** [comment]
mmmm, events include more than fomorians and razorbacks, fyi.

**Comment by MainlandHero** [comment]
@aliasfalse Do you happen to have a list of events your parser expects?

**Comment by aliasfalse** [comment]
It's anything that shows up in the Goals array

**Comment by TobiTenno** [comment]
Do we wanna work on a format for this with the jumbotron stuff soon?
I think the jumbotron is a good idea, since it'd call it out, and we can still add checks (component selection) for it, and just leave it out of whatever drag/drop strategy we choose, since it's purpose is "hey, something's going on"....

![image](https://user-images.githubusercontent.com/7128721/34528765-8570d798-f06f-11e7-8a14-3b2cab17b793.png)


one other possibility i can think that would be cool is if we use something like an alert for when it first pops up (warning or heads up).

![image](https://user-images.githubusercontent.com/7128721/34528713-6364015c-f06f-11e7-9925-bb1574345933.png)

or should it be green, since it'd be "important"?

![image](https://user-images.githubusercontent.com/7128721/34528743-75571e44-f06f-11e7-83fe-ac59db20e116.png)
