### ISSUE TITLE
 Baro timer shows off by 2 days

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-hub#647]
### Summary

Baro's timer is always 2 days late for the start while he's traveling

![image](https://user-images.githubusercontent.com/7128721/145594551-916ca74b-6967-4ff8-a3ce-5bc4ba5051f9.png)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Brave

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyAyEm** [comment]
From what i saw it seems that a [TimeBadge ](https://github.com/WFCD/warframe-hub/blob/dev/src/components/TimeBadge.vue#L105)displays the time to the end not the start, and that's causing the problem. Since the generic approach of TimeBadge i don't know what an appropriate solution would be.

**Comment by D1firehail** [comment]
I got curious and investigated a bit. `diffactivate` is roughly equal to negative current unix timestamp when it should be the difference between now and the start time (negative if after, positive if before).  
`diff`, which is the equivalent variable but comparing against end time rather than start time, does actually have the correct value.

[diff calculation](https://github.com/WFCD/warframe-hub/blob/740fb31678db8443c19d122d41e2fa0902ae8a19/src/components/TimeBadge.vue#L105) vs [diffactivate calculation](https://github.com/WFCD/warframe-hub/blob/740fb31678db8443c19d122d41e2fa0902ae8a19/src/components/TimeBadge.vue#L97) 
Problem is probably using `dayjs(start).unix()` instead of `dayjs.unix(start)`
Don't have a dev environment set up for js so can't verify myself
